[information]
 name = "dracula"
 background = "dark"
 author = 'Max Miliano'

[palette]
 fg = '#f8f8f2'
 bg = '#282a36'
 float_bg = '#23252f'
 currentline = '#44475a'
 comment = '#6272a4'
 cyan = '#8be9fd'
 green = '#50fa7b'
 orange = '#ffb86c'
 pink = '#ff79c6'
 purple = '#bd93f9'
 red = '#ff5555'
 yellow = '#f1fa8c'
 cursor_fg = '#282a36'
 cursor_bg = '#f8f8f2'
 sign_add = '#50fa7b'
 sign_change = '#ffb866'
 sign_delete = '#ff5555'
 tree_sign_add = '#50fa7b'
 tree_sign_change = '#ffb866'
 error = '#ff555b'
 warning = '#ffb866'
 info = '#8be9fd'
 hint = '#8be9fd'
 other = '#bd93f9'

[highlights]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'link:Normal'
 ModeMsg = 'fg bg b'
 MsgSeparator = 'fg bg b'
 SpellBad = 'error - u'
 SpellCap = 'info - u'
 SpellLocal = 'warning - u'
 SpellRare = 'other - u'
 NormalNC = 'link:Normal'
 Pmenu = 'link:Normal'
 PmenuSel = '- currentline'
 WildMenu = '- bg b'
 CursorLineNr = 'pink bg'
 Comment = 'comment - i'
 Folded = 'comment currentline'
 FoldColumn = 'fg bg'
 LineNr = 'comment bg'
 FloatBorder = 'comment float_bg'
 Whitespace = 'bg -'
 WinSeparator = 'comment -'
 VertSplit = 'link:WinSeparator'
 CursorLine = '- currentline'
 CursorColumn = 'link:CursorLine'
 ColorColumn = 'link:CursorColumn'
 NormalFloat = 'fg float_bg'
 Visual = '- currentline'
 VisualNOS = 'link:Visual'
 WarningMsg = 'warning bg'
 DiffAdd = 'sign_add - r'
 DiffChange = 'sign_change - r'
 DiffDelete = 'sign_delete - r'
 QuickFixLine = '- currentline b'
 PmenuSbar = '- bg'
 PmenuThumb = '- fg'
 MatchWord = '- - u'
 MatchParen = 'hint bg u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 Conceal = 'pink'
 Directory = 'pink'
 SpecialKey = 'purple - b'
 Title = 'cyan - b'
 ErrorMsg = 'error bg b'
 Search = 'link:Visual'
 IncSearch = 'fg - b'
 Substitute = 'link:IncSearch'
 MoreMsg = 'cyan - b'
 Question = 'cyan - b'
 EndOfBuffer = 'bg'
 NonText = 'bg'
 Variable = 'fg'
 String = 'yellow'
 Character = 'yellow'
 Constant = 'purple'
 Number = 'purple'
 Boolean = 'purple'
 Float = 'link:Number'
 Identifier = 'green'
 Function = 'link:Identifier'
 Operator = 'pink'
 Type = 'cyan - i'
 StorageClass = 'pink'
 Structure = 'pink'
 Typedef = 'pink'
 Keyword = 'pink'
 Statement = 'pink'
 Conditional = 'pink'
 Repeat = 'pink'
 Label = 'pink'
 Exception = 'pink'
 Include = 'pink'
 PreProc = 'pink'
 Define = 'pink'
 Macro = 'pink'
 PreCondit = 'pink'
 Special = 'pink'
 SpecialChar = 'pink'
 Tag = 'cyan'
 Debug = 'pink'
 Delimiter = 'fg -'
 SpecialComment = 'pink'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'purple bg b'
 Todo = 'cyan - b'
 Error = 'error bg b'
 TabLine = 'comment bg'
 TabLineSel = 'link:Normal'
 TabLineFill = '- bg'

[TreeSitter]
 '@comment' = 'comment'
 '@comment.documentation' = 'comment'
 '@error' = 'link:Error'
 '@operator' = 'pink'
 '@punctuation.delimiter' = 'fg'
 '@punctuation.delimiter.cpp' = 'pink'
 '@punctuation.bracket' = 'pink'
 '@punctuation.special' = 'pink'
 '@string' = 'yellow'
 '@string.regex' = 'red'
 '@string.escape' = 'pink'
 '@string.special' = 'pink'
 '@character' = 'yellow'
 '@character.special' = 'pink'
 '@function' = 'green'
 '@function.builtin' = 'green'
 '@function.call' = 'green'
 '@method' = 'green'
 '@method.call' = 'green'
 '@constructor' = 'pink'
 '@constructor.c_sharp' = 'link:@type'
 '@constructor.php' = 'link:@type'
 '@parameter' = 'orange - i'
 '@boolean' = 'purple'
 '@number' = 'purple'
 '@float' = 'purple'
 '@exception' = 'link:Exception'
 '@type' = 'link:Type'
 '@type.dart' = 'link:@type'
 '@type.builtin' = 'cyan - i'
 '@type.builtin.cpp' = 'pink - i'
 '@type.definition' = 'link:Type'
 '@type.qualifier' = 'pink'
 '@storageclass' = 'pink'
 '@attribute' = 'pink'
 '@field' = 'cyan - i'
 '@property' = 'fg'
 '@variable' = 'fg'
 '@variable.builtin' = 'purple'
 '@constant' = 'purple'
 '@constant.builtin' = 'purple'
 '@constant.macro' = 'purple'
 '@namespace' = 'fg'
 '@symbol' = 'purple'
 '@text' = 'yellow'
 '@text.strong' = 'orange - b'
 '@text.emphasis' = 'green - i'
 '@text.strike' = 'yellow - s'
 '@text.title' = 'cyan - b'
 '@text.literal' = 'green - i'
 '@text.quote' = 'pink'
 '@text.uri' = 'cyan'
 '@text.math' = 'pink'
 '@text.reference' = 'pink'
 '@text.todo' = 'link:Todo'
 '@text.warning' = 'link:WarningMsg'
 '@text.danger' = 'link:ErrorMsg'
 '@text.diff.add' = 'link:DiffAdd'
 '@text.diff.delete' = 'link:DiffDelete'
 '@tag' = 'pink'
 '@tag.attribute' = 'green'
 '@tag.delimiter' = 'fg'

[Semantic]
 '@lsp.type.namespace' = 'link:@namespace'
 '@lsp.type.type' = 'link:@type'
 '@lsp.type.class' = 'link:@type'
 '@lsp.type.enum' = 'link:@type'
 '@lsp.type.interface' = 'link:@type'
 '@lsp.type.struct' = 'link:@structure'
 '@lsp.type.parameter' = 'link:@parameter'
 '@lsp.type.variable' = 'link:@variable'
 '@lsp.type.property' = 'link:@property'
 '@lsp.type.enumMember' = 'link:@constant'
 '@lsp.type.function' = 'link:@function'
 '@lsp.type.method' = 'link:@method'
 '@lsp.type.macro' = 'link:@macro'
 '@lsp.type.decorator' = 'link:@function'
 '@lsp.typemod.variable.defaultLibrary' = 'link:@constant'
 '@lsp.typemod.parameter.readyonly' = 'link:Italic'
 '@lsp.typemod.variable.readonly' = 'link:@variable.builtin'

[Whichkey]
 WhichKey = 'fg'
 WhichKeyValue = 'pink'
 WhichKeySeperator = 'pink'
 WhichKeyGroup = 'green'
 WhichKeyDesc = 'cyan'
 WhichKeyFloat = '- float_bg'

[Git]
 SignAdd = 'sign_add'
 SignChange = 'sign_change'
 SignDelete = 'sign_delete'
 GitSignsAdd = 'sign_add'
 GitSignsChange = 'sign_change'
 GitSignsDelete = 'sign_delete'

[LSP]
 LspDiagnosticsDefaultError = 'error'
 LspDiagnosticsDefaultWarning = 'warning'
 LspDiagnosticsDefaultInformation = 'info'
 LspDiagnosticsDefaultInfo = 'info'
 LspDiagnosticsDefaultHint = 'hint'
 LspDiagnosticsVirtualTextError = 'error'
 LspDiagnosticsVirtualTextWarning = 'warning'
 LspDiagnosticsVirtualTextInformation = 'info'
 LspDiagnosticsVirtualTextInfo = 'info'
 LspDiagnosticsVirtualTextHint = 'hint'
 LspDiagnosticsFloatingError = 'error'
 LspDiagnosticsFloatingWarning = 'warning'
 LspDiagnosticsFloatingInformation = 'info'
 LspDiagnosticsFloatingInfo = 'info'
 LspDiagnosticsFloatingHint = 'hint'
 DiagnosticSignError = 'error'
 DiagnosticSignWarning = 'warning'
 DiagnosticSignInformation = 'info'
 DiagnosticSignInfo = 'info'
 DiagnosticSignHint = 'hint'
 LspDiagnosticsSignError = 'error'
 LspDiagnosticsSignWarning = 'warning'
 LspDiagnosticsSignInformation = 'info'
 LspDiagnosticsSignInfo = 'info'
 LspDiagnosticsSignHint = 'hint'
 LspDiagnosticsError = 'error'
 LspDiagnosticsWarning = 'warning'
 LspDiagnosticsInformation = 'info'
 LspDiagnosticsInfo = 'info'
 LspDiagnosticsHint = 'hint'
 LspDiagnosticsUnderlineError = '- - u'
 LspDiagnosticsUnderlineWarning = '- - u'
 LspDiagnosticsUnderlineInformation = '- - u'
 LspDiagnosticsUnderlineInfo = '- - u'
 LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- float_bg'
 LspReferenceText = '- float_bg'
 LspReferenceWrite = '- float_bg'

[Telescope]
 TelescopeNormal = 'link:NormalFloat'
 TelescopeSelection = 'hint'
 TelescopeMatching = 'info - b'
 TelescopeBorder = 'link:WinSeparator'

[NvimTree]
 NvimTreeFolderIcon = 'link:Directory'
 NvimTreeIndentMarker = 'link:Directory'
 NvimTreeNormal = 'link:Normal'
 NvimTreeWinSeparator = 'link:WinSeparator'
 NvimTreeVertSplit = 'link:VertSplit'
 NvimTreeFolderName = 'fg'
 NvimTreeOpenedFolderName = 'pink - b'
 NvimTreeEmptyFolderName = 'pink - i'
 NvimTreeGitIgnored = 'comment - i'
 NvimTreeEndOfBuffer = 'link:EndOfBuffer'
 NvimTreeCursorLine = 'link:CursorLine'
 NvimTreeGitStaged = 'sign_add'
 NvimTreeGitNew = 'sign_add'
 NvimTreeGitRenamed = 'sign_add'
 NvimTreeGitDeleted = 'sign_delete'
 NvimTreeGitMerge = 'sign_change'
 NvimTreeGitDirty = 'sign_change'

[StatusLine]
 StatusLine = 'fg float_bg'
 StatusLineNC = 'float_bg float_bg'
 StatusLineSeparator = 'float_bg'
 StatusLineTerm = 'float_bg'
 StatusLineTermNC = 'float_bg'

[Dashboard]
 DashboardHeader = 'cyan - b'
 DashboardCenter = 'fg'
 DashboardFooter = 'pink'

[Cmp]
 CmpItemAbbrDeprecated = 'comment - s'
 CmpItemKindFunction = 'link:@function'
 CmpItemKindMethod = 'link:@method'
 CmpItemKindConstructor = 'link:@constructor'
 CmpItemKindClass = 'link:@storageclass'
 CmpItemKindEnum = 'link:@Constant'
 CmpItemKindInterface = 'link:@type'
 CmpItemKindStruct = 'link:@storageclass'
 CmpItemKindVariable = 'link:@variable'
 CmpItemKindField = 'link:@field'
 CmpItemKindProperty = 'link:@property'
 CmpItemKindEnumMember = 'link:@constant'
 CmpItemKindConstant = 'link:@constant'
 CmpItemKindKeyword = 'link:@keyword'
 CmpItemKindFile = 'fg'
 CmpItemKindFolder = 'cyan'
 CmpItemKindOperator = 'link:@operator'
 CmpItemKindTypeParameter = 'link:@parameter'

